variables:
  #依據要在efp server上起的container命名docker image，在此更改，下方build image會從這裡獲取variables
  #PROJECT_NAME: 規則ftp-{layer}-{job describe}
  DOCKER_IMAGE_NAME: "efp-environment-check"
  DOCKER_IMAGE_TAG: "latest"
  GIT_SSL_NO_VERIFY: "true" #忽略SSL驗證

stages:
  - build-image

before_script:
  - docker info

build-image:
  # 以下一行的image執行接下來的build過程，要執行docker command是使用以下image
  image: harbor.wistron.com/base_image/docker:stable
  # image: harbor.wistron.com/base_image/gitleaks:latest # gitleaks是掃描secret的
  stage: build-image
  tags: 
    - k8s-runners

  script:
    #用gitlab專案的setting->cicd->variables設定好的變數取代config.cfg內容值
    - sed -i "s/%password/$PASSWORD/" /${CI_PROJECT_DIR}/config.cfg
    - sed -i "s/%username/$USERNAME/" /${CI_PROJECT_DIR}/config.cfg
    - sed -i "s/%line_authorization/$LINE_Authorization/" /${CI_PROJECT_DIR}/config.cfg
    - sed -i "s/%line_me_authorization/$LINE_me_Authorization/" /${CI_PROJECT_DIR}/config.cfg
    - sed -i "s/%postgresql_user/$PostgreSQL_USER/" /${CI_PROJECT_DIR}/config.cfg
    - sed -i "s/%postgresql_pw/$PostgreSQL_PW/" /${CI_PROJECT_DIR}/config.cfg
    - sed -i "s/%postgresql_host/$PostgreSQL_HOST/" /${CI_PROJECT_DIR}/config.cfg
    - sed -i "s/%postgresql_db/$PostgreSQL_DB/" /${CI_PROJECT_DIR}/config.cfg
    - sed -i "s/%postgresql_port/$PostgreSQL_PORT/" /${CI_PROJECT_DIR}/config.cfg

    - echo $DOCKER_IMAGE_NAME
    - echo $DOCKER_IMAGE_TAG
    #--rm=true即整個購建過程成功後刪除中間環節的容器
    - docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} --rm=true .
    - docker tag ${DOCKER_IMAGE_NAME} harbor.wistron.com/k8sprdwihaiot/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin $DOCKER_REGISTRY
    - docker push harbor.wistron.com/k8sprdwihaiot/${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
